version: "3.8"
name: local-infrastructure-kafka

services:
  zookeeper-local:
    container_name: zookeeper-local
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"
    networks:
      - local-network

  kafka-local:
    container_name: kafka-local
    image: wurstmeister/kafka:2.13-2.8.1
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-local:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_DELETE_TOPIC_ENABLE: "true"
    volumes:
      - ./kafka-data:/kafka-data
    networks:
      - local-network

volumes:
  kafka-data:
    driver: local

networks:
  local-network:
    driver: bridge
